### ISSUE TITLE
Amazon Web Services support

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/bifravst#1]
Implement the *Cat Tracker* sample on [Amazon Web Services](https://aws.amazon.com/) (AWS).

The high level features are:

- devices can connect to the broker
- devices can send data to the broker and read configuration
- users can use the web app to see the sensor data from the devices

For this to work this needs to be done:

- [x] Set up AWS IoT for Just-in-time provisioning with Device Policy
- [x] Instructions for user on how to create a CA
- [x] Build Single-Page-Application (SPA)
- [x] Set up deployment of SPA
- [x] Historical Data pipeline
- [x] Show historical data on UI
- [x] Device configuration
- [x] Add firmware example 
- [x] DFU

![AWS Components](https://user-images.githubusercontent.com/188915/61143143-b434f380-a4d1-11e9-8cc3-fd8e396828a0.jpg)
