### ISSUE TITLE
Google Cloud Platform (GCP) support

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/bifravst#25]
https://github.com/bifravst/gcp

Porting the [AWS-based](https://github.com/bifravst/aws) implementation to
[Google Cloud Platform](https://cloud.google.com/) (GCP) means finding the
equivalent services:

| Feature                  | AWS                                                                                                   | GCP                                                                                                                                                                                     |
| ------------------------ | ----------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| MQTT Broker              | [IoT Core](https://aws.amazon.com/iot-core/)                                                          | [IoT](https://cloud.google.com/solutions/iot/)                                                                                                                                          |
| Historical Data Analysis | [Athena](https://aws.amazon.com/athena/)                                                              | [BigQuery](https://cloud.google.com/bigquery/)                                                                                                                                          |
| Website Hosting          | [CloudFront](https://aws.amazon.com/cloudfront/) + [S3](https://aws.amazon.com/s3/)                   | [Firebase Hosting](https://firebase.google.com/docs/hosting/)                                                                                                                           |
| CI/CD                    | [CodeBuild](https://aws.amazon.com/codebuild/) + [CodePipeline](https://aws.amazon.com/codepipeline/) | [Cloud Build](https://cloud.google.com/cloud-build/)                                                                                                                                    |
| User Authentication      | [Cognito](https://aws.amazon.com/cognito/)                                                            | [Identity Platform](https://cloud.google.com/identity-platform/) which is the same as [Firebase Authentication](https://firebase.google.com/docs/auth)                                  |
| Infrastructure as Code   | [CDK](https://aws.amazon.com/cdk/)                                                                    | [Deployment Manager](https://cloud.google.com/deployment-manager/) ([Supported GCP type providers](https://cloud.google.com/deployment-manager/docs/configuration/supported-gcp-types)) |

## 9160 support for GCP

- https://devzone.nordicsemi.com/f/nordic-q-a/58892/unable-to-receive-messages-on-google-cloud-from-client-thingy91-using-mqtt-protocol

## Features

taken from
[the AWS implementation's features](https://github.com/bifravst/aws/tree/68011a5a7fbd51c4c8c1be634dc00180dafe4869/features)

- [ ] Look into
      [TerraForm](https://www.terraform.io/docs/providers/google/r/cloudiot_registry.html)
      to set up all resources
- [x] Connect a Cat Tracker
- [x] └ Generate a certificate and connect
- [x] Device: Update Shadow
- [x] └ Publish device information to desired state
- [ ] Update Device Configuration
- [ ] └ Update the device configuration as a user
- [ ] Read Device Shadow
- [ ] └ Read reported and desired state as user
- [ ] Query Data
- [ ] └ Query historical data
- [ ] List cats
- [ ] └ The user should be able to list cats
- [ ] Device Firmware Upgrade over the air
- [ ] ├ Create a new firmware upgraded as a user
- [ ] ├ Fetch the job as a device and mark as in progress
- [ ] ├ describe the job
- [ ] ├ cancel the job
- [ ] └ delete the job
- [ ] Device: Batch Data
- [ ] ├ Devices can publish batch data
- [ ] └ Query the historical gps data
- [ ] Delete cats
- [ ] └ Delete the certificate
- [ ] Delete a user
- [ ] └ un-assign the IoT policy
- [ ] Uninstall

## Notes

The IoT Core does not support websockets, so in order to have real-time updates
on the web app a possible solution seems to be
[like this](https://cloud.google.com/community/tutorials/cloud-iot-rtdp):
trigger a cloud function which publishes to Firebase Messaging.
