### ISSUE TITLE
Microsoft Azure support

### ISSUE THREAD

**Issue by coderbyheart** [bifravst/bifravst#29]
https://github.com/bifravst/azure

# Service Equivalents

Porting the [AWS-based](https://github.com/bifravst/aws) implementation to
[Microsoft Azure](https://azure.microsoft.com/) (Azure) means finding the
equivalent services:

| Feature                  | AWS                                                                                                   | Azure                                                                                                                    |
| ------------------------ | ----------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------ |
| MQTT Broker              | [IoT Core](https://aws.amazon.com/iot-core/)                                                          | [IoT Hub](https://azure.microsoft.com/en-us/services/iot-hub/), [Event Grid](https://azure.microsoft.com/en-us/updates/device-telemetry-events-from-iot-hub-to-event-grid/)                                                           |
| Historical Data Analysis | [Athena](https://aws.amazon.com/athena/)                                                              | ~[Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-iot-hub)~ ¹ - ~[Synapse Analytics](https://docs.microsoft.com/en-us/azure/synapse-analytics/sql/query-json-files)~ [²](https://github.com/bifravst/bifravst/issues/29#issuecomment-639410428) [Cosmos DB](https://docs.microsoft.com/en-us/azure/cosmos-db/introduction) [³](https://github.com/bifravst/bifravst/issues/29#issuecomment-639410428) (minimum price per month: ~24 USD) |
| Website Hosting          | [CloudFront](https://aws.amazon.com/cloudfront/) + [S3](https://aws.amazon.com/s3/)                   | [Blob Storage](https://azure.microsoft.com/en-us/services/storage/)                                                           |
| CI/CD                    | [CodeBuild](https://aws.amazon.com/codebuild/) + [CodePipeline](https://aws.amazon.com/codepipeline/) | [ARM with GitHub Actions](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-github-actions)                                                                                                                        |
| User Authentication      | [Cognito](https://aws.amazon.com/cognito/)                                                            | [Active Directory B2C](https://azure.microsoft.com/en-us/services/active-directory-b2c/)                                 |
| Infrastructure as Code   | [CDK](https://aws.amazon.com/cdk/)                                                                    | [Resource Manager Templates](https://docs.microsoft.com/en-us/azure/azure-resource-manager/template-deployment-overview) |

¹ The minimum price for Azure Data Explore per month is around $220.

## Resources

- [Azure IoT Monitoring example](https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet)
- [Microsoft Azure IoT SDK for Node.js](https://github.com/Azure/azure-iot-sdk-node)
- [Create IoT Hub and Device to Cloud Consumer Group](https://github.com/Azure/azure-quickstart-templates/tree/master/101-iothub-with-consumergroup-create/)
- [Microsoft Identity Platform: Single-page applications](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-overview)
- [Build Nodejs APIs using Serverless on Azure - Simona Cotin](https://www.youtube.com/watch?v=D2_ts6Y5UyE)
- [How to Deploy your Azure Function Automatically with ARM template (4 different ways)](http://www.frankysnotes.com/2019/07/four-ways-to-deploy-your-azure-function.html)
- [How to Deploy your Azure Functions Faster and Easily with Zip Push](http://www.frankysnotes.com/2018/06/how-to-deploy-your-azure-functions.html)
- [Improving the TypeScript support in Azure Functions](https://azure.microsoft.com/en-us/blog/improving-the-typescript-support-in-azure-functions/)
- [Moving from Lambda to Azure Functions (6 Part Series)](https://dev.to/azure/move-a-simple-javascript-node-js-aws-lambda-function-to-azure-431l)
- [Work with Azure functions locally](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?WT.mc_id=awsmigration-youtube-jeliknes)
- [Course: Create serverless applications](https://docs.microsoft.com/en-us/learn/paths/create-serverless-applications/?WT.mc_id=awsmigration-youtube-jeliknes)
- [Azure IoT reference architecture](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/iot/):
  The reference architecture looks good, in my experience FOTA is a critical
  component, which is not covered in that architecture (although mentioned in
  the User management section). Guides for this
  [exist already](https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-firmware-update).
  The [sample implementation](https://github.com/mspnp/iot-guidance) does not
  follow this architecture (it omits the Active Directory part) and is basically
  a giant TODO list, it hasn't been updated in over a year, no CI/CD tests
  ensure that this implementation actually works. Deployment is a barely
  document multi-step process
  ([this is just for one sub-component, the HotPath](https://github.com/mspnp/iot-guidance/blob/master/src/HotPath/readme.md)),
  and seems to depend on VS Code. Finally, both architectures seem to target
  business internal deployments, use of Active Directory suggests, that it's
  assumed that this will be deployed alongside an existing organization's AD to
  allow employees (pre-known users) access to the solution. This is not suitable
  for the architecture I want: It should implement a B2C solution, where user
  sign up and have access to their devices. This also works for internal
  deployments, but the key is to have a separate user directory, that's why I am
  using Active Directory B2C as an authentication provider for the SPA.
- [Azure FOTA Tutorial](https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-firmware-update) is still the current reference template for implementing FOTA

## Notes

- Authentication in Browser:
  [`msal`](https://github.com/AzureAD/microsoft-authentication-library-for-js)
  is recommended, but not yet supported by the `@azure/arm-*` packages:
  https://github.com/Azure/azure-sdk-for-js/issues/2556#issuecomment-497505818,
  use [`ms-rest-browserauth`](https://github.com/Azure/ms-rest-browserauth)
  instead:
  [Example](https://www.npmjs.com/package/@azure/arm-iothub#browser---authentication-client-creation-and-list-operations-as-an-example-written-in-javascript)
- Authenticate using
  [Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/)
  - [What is Azure Active Directory B2C?](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-overview)
  - [Single-Page Application built on MSAL.js with Azure AD B2C](https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-b2c-javascript-msal-singlepageapp/single-page-application-built-on-msaljs-with-azure-ad-b2c/)
    - [GatsbyJS: Deploying to Azure](https://www.gatsbyjs.org/docs/deploying-to-azure/)
  - [Adding Azure AD B2C Authentication to Azure Functions](https://codemilltech.com/adding-azure-ad-b2c-authentication-to-azure-functions/)
  - [Using Managed Service Identity (MSI) with an Azure App Service or an Azure Function](https://blogs.msdn.microsoft.com/benjaminperkins/2018/06/13/using-managed-service-identity-msi-with-and-azure-app-service-or-an-azure-function/)
- nRF91 can now connect to Azure: https://devzone.nordicsemi.com/support/242278
- Synapse Analytics
  - [Query JSON files using SQL on-demand (preview) in Azure Synapse Analytics](https://docs.microsoft.com/en-us/azure/synapse-analytics/sql/query-json-files)
  - [Quickstart: Use Synapse Studio (preview)](https://docs.microsoft.com/en-us/azure/synapse-analytics/quickstart-synapse-studio)
- End-to-end tests (https://github.com/bifravst/azure/pull/23)
  - need a different issuer URL: https://bifravstprod.b2clogin.com/bifravstprod.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_developer (https://twitter.com/coderbyheart/status/1291049057109061638)

## Features

taken from
[the AWS implementation's features](https://github.com/bifravst/aws/tree/68011a5a7fbd51c4c8c1be634dc00180dafe4869/features)

- [x] Look into
      [Azure Resource Manager](https://azure.microsoft.com/en-us/features/resource-manager/)
      to set up all resources
- [x] Look into [App Service Static Web Apps](https://techcommunity.microsoft.com/t5/azure-app-service/introducing-app-service-static-web-apps/ba-p/1394451?WT.mc_id=staticwebapps-social-wachegha)
- [x] add role assignment (azure functions need to access IoT hub) to ARM
- [x] remember to use B2C web app in website authentication (client id, and
      Issuer URL:
      `https://bifravstwebsite.azurewebsites.net/.auth/login/aad/callback`)
- [x] Connect a Cat Tracker
- [x] └ Generate a certificate and connect
- [x] Device: Update Shadow
- [x] └ Publish device information to desired state
- [x] Update Device Configuration
- [x] └ Update the device configuration as a user
- [ ] How to retrieve config object only (2304 byte size limit!)
- [x] Read Device Shadow
- [x] └ Read reported and desired state as user
- [x] Query Data
- [x] └ Query historical data
- [x] List cats
- [x] ├ list cats
- [x] ├ view a cat
- [x] ├ name/rename a cat
- [x] └ assign a picture to a cat
- [x] Device Firmware Upgrade over the air
- [x] ├ Create a new firmware upgraded as a user
- [x] ├ Fetch the job as a device and mark as in progress
- [x] ├ describe the job
- [x] └ cancel the job
- [x] Device: Batch Data
- [x] ├ Devices can publish batch data
- [x] └ Query the historical gps data
- [x] Delete cats
- [x] └ Delete the certificate
- [ ] Delete a user
- [ ] Uninstall
- [x] Docs: Running the App & Deploying

## End-to-end tests

- [x] Feature:  Register a new account
- [x] └ Scenario: Sign up 
- [x] ~~├ Scenario: Initially the user should not have policies~~
- [x] ~~└ Scenario: Self-assign the policy~~
- [x] Feature:  Connect a Cat Tracker
- [x] └ Scenario: Generate a certificate and connect 
- [x] Feature:  Device: Update Shadow
- [x] └ Scenario: Publish device information to reported state 
- [x] Feature:  Update Device Configuration
- [x] └ Scenario: Update the device configuration as a user 
- [x] Feature:  Read Device Shadow
- [x] └ Scenario: Read reported and desired state as user 
- [x] Feature:  Query Data
- [x] └ Scenario: Query historical data 
- [x] Feature:  List cats
- [x] └ Scenario: The user should be able to list cats 
- [x] Feature:  Device Firmware Upgrade over the air
- [x] ├ Scenario: Create a new firmware upgraded as a user 
- [x] ├ Scenario: Fetch the job as a device and mark as in progress 
- [x] ├ Scenario: describe the job 
- [x] ├ Scenario: cancel the job 
- [x] └ Scenario: delete the job 
- [x] Feature:  Device: Messages
- [x] ├ Scenario: Devices publishes that a button was pressed 
- [x] └ Scenario: Query the message data 
- [x] Feature:  Device: Batch Data
- [x] ├ Scenario: Devices can publish batch data 
- [x] └ Scenario: Query the historical gps data 
- [ ] Feature:  Cell Geolocation Publish API
- [ ] ├ Scenario: Provide cell geolocation 
- [ ] └ Scenario: Query a cell 
- [x] Feature:  Cell Geolocation API
- [x] ├ Scenario: Device enters a cell 
- [x] ├ Scenario: Device acquires a GPS fix 
- [x] ├ Scenario: Query a cell: first time 
- [x] └ Scenario: Query a cell 
- [x] Feature:  Delete cats
- [x] └ Scenario: Delete the certificate 
- [ ] Feature:  Delete a user
- [ ] └ Scenario: un-assign the IoT policy

**Comment by coderbyheart** [comment]
Having issues with connecting the device using DSP enrollment group: https://social.msdn.microsoft.com/Forums/en-US/9b52c301-963c-42c2-bb31-503b2a258d40/connect-to-iothub-using-dsp-enrollment-group-and-x509-certificate-error-could-not-connect?forum=azureiothub

**Comment by coderbyheart** [comment]
Check out https://twitter.com/manekinekko/status/1262798883182317568?s=19

**Comment by coderbyheart** [comment]
I managed to get a Synapse Analytics workgroup in place (https://github.com/bifravst/azure/commit/9897bd457e4517aacd9048afb53ee7db3ee45a1d), but struggle with some authentication problems: 

![image](https://user-images.githubusercontent.com/188915/83869033-2d61b880-a72c-11ea-9406-d20b6bbc709e.png)


However, I have revisited the idea to use Cosmos DB, and I think it might be the better choice after all ... Developers on Azure should be more familiar with this than Synapse Analytics, ... and it offers an SQL query interface (I initially thought it was a document DB with an interface like MongoDB/CouchDB) ... This provides the flexibility I want and in general a product that should be easier to understand and get running compared to Synapse Analytics.

https://twitter.com/coderbyheart/status/1268920341746851841
